spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportsController
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

