spring:
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    url: jdbc:postgresql://192.168.0.208:5432/reportsController
    username: admin
    password: admin
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    types:
      print:
        banner: false
      type_contributors: com.vladmihalcea.hibernate.type.joda.JodaTimeTypeContributor
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  logging:
    level:
      org:
        springframework:
          data: DEBUG
        hibernate: DEBUG
