version: '3.8'
services:
    postgres:
        container_name: postgresql
        image: postgres:14.5
        restart: always
        environment:
          - POSTGRES_DB=reportsController
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data